# Generated by Django 5.0.2 on 2024-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatShare",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=10)),
                ("seats_held", models.IntegerField()),
                ("election_year", models.IntegerField()),
                ("total_seats", models.IntegerField()),
            ],
        ),
    ]
