# Generated by Django 5.0.2 on 2024-04-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seatshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_bond_number', models.CharField(max_length=7)),
                ('amount', models.IntegerField()),
                ('donor_name', models.CharField(max_length=61)),
                ('party_name', models.CharField(max_length=37)),
            ],
        ),
    ]
