# Generated by Django 5.0.2 on 2024-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_seatshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="LSElection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=10)),
                ("state_name", models.CharField(max_length=30)),
                ("constituency_name", models.CharField(max_length=30)),
                ("candidate_name", models.CharField(max_length=30)),
                ("election_year", models.IntegerField()),
                ("candidate_position", models.FloatField()),
                ("margin_percentage", models.IntegerField()),
            ],
        ),
    ]
