# Generated by Django 5.0.2 on 2024-03-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seatshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralBondCDenomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=50)),
                ('denomination', models.IntegerField()),
            ],
        ),
    ]
