# Generated by Django 5.0.2 on 2024-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_lselection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lselection",
            old_name="candidate_name",
            new_name="candidate",
        ),
    ]
