# Generated by Django 5.0.2 on 2024-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_lselection_candidate_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lselection",
            name="vote_share",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lselection",
            name="margin_percentage",
            field=models.FloatField(default=0),
        ),
    ]
