# Generated by Django 5.0.2 on 2024-03-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_lselection_vote_share_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lselection",
            name="margin_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="lselection",
            name="vote_share",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
