# Generated by Django 5.0.2 on 2024-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_lselection_margin_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lselection",
            name="constituency_no",
            field=models.IntegerField(default=0),
        ),
    ]
