# Generated by Django 5.0.2 on 2024-04-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_campaignfinance"),
        ("app", "0008_lselection_constituency_no"),
    ]

    operations = []
