# Generated by Django 5.0.2 on 2024-05-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_merge_20240416_2248"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoknitiCodebook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_year", models.IntegerField()),
                ("question_var", models.CharField(max_length=10)),
                ("question_text", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="LoknitiResponders",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_year", models.IntegerField()),
                ("state_name", models.CharField(max_length=50)),
                ("PC_id", models.IntegerField()),
                ("AC_id", models.IntegerField()),
                ("respondent_no", models.IntegerField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=50)),
                ("caste", models.CharField(max_length=50)),
                ("religion", models.CharField(max_length=100)),
                ("income", models.FloatField(default=0)),
                (
                    "education_level",
                    models.CharField(default="No response", max_length=50),
                ),
                ("occupation", models.CharField(default="No response", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LoknitiResponses",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respondent_no", models.IntegerField()),
                ("election_year", models.IntegerField()),
                ("question_var", models.CharField(max_length=20)),
                ("response", models.CharField(max_length=500)),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loknitiresponders",
                    ),
                ),
            ],
        ),
    ]
