# Generated by Django 5.0.2 on 2024-05-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_lokniticodebook_loknitiresponders_loknitiresponses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loknitiresponders",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="loknitiresponders",
            name="caste",
            field=models.CharField(default="No response", max_length=50),
        ),
        migrations.AlterField(
            model_name="loknitiresponders",
            name="gender",
            field=models.CharField(default="No response", max_length=50),
        ),
        migrations.AlterField(
            model_name="loknitiresponders",
            name="religion",
            field=models.CharField(default="No response", max_length=100),
        ),
        migrations.AlterField(
            model_name="loknitiresponders",
            name="respondent_no",
            field=models.IntegerField(default=0),
        ),
    ]
