# Generated by Django 5.0.2 on 2024-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_loknitiresponders_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loknitiresponders",
            name="PS_id",
            field=models.IntegerField(default=0),
        ),
    ]
