# Generated by Django 5.0.2 on 2024-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_loknitiresponders_ps_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loknitiresponders",
            name="income",
            field=models.CharField(default="No response", max_length=100),
        ),
    ]
