# Generated by Django 5.0.2 on 2024-05-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_loknitiresponders_ac_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loknitiresponses',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lokniticodebook'),
        ),
        migrations.AlterField(
            model_name='loknitiresponses',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.loknitiresponders'),
        ),
    ]
