# Generated by Django 5.0.2 on 2024-05-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_loknitiresponses_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loknitiresponses',
            name='election_year',
        ),
        migrations.RemoveField(
            model_name='loknitiresponses',
            name='respondent_no',
        ),
    ]
